spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sp1?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: shams123@
    driver-class-name: com.mysql.jdbc.Driver
